# Generated by Django 2.2.7 on 2020-05-16 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jasoseolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasoseol',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
