# Generated by Django 2.2.7 on 2020-05-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasoseolapp', '0002_jasoseol_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasoseol',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
