# Generated by Django 2.2.7 on 2020-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasoseolapp', '0003_auto_20200517_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasoseol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
